### PR TITLE
Group signatories into orgs and individuals and sort them by first character (case insensitive)

### PR DESCRIPTION
**Pull request by mjgiarlo**
I created this PR to better see what #233 would look like. This is primarily to advance discussion on #233, though I'm fine with it getting merged, also.

Sorting the list of names may mean fewer merge conflicts as we go forward, though it comes at the cost of making folks find the right spot to insert their own names or organizations.

A few content changes I made:

* I broke the PKP signature out to individual and organizational ones (I believe this is faithful to the original signature).
* I shifted DCE's initialism to the end of the line.
* I added an initialism to ARL.

### CODE REVIEW

**Comment by gmcharlt** [comment]
I'm fine with this approach and the decisions you've made and would be a +1 to merge (after a rebase)

**Comment by matt-bernhardt** [comment]
All this makes a lot of sense to me - thanks! +1 to merge when rebased.

**Comment by ranti** [comment]
+1

**Comment by mjgiarlo** [comment]
Pls do not merge until we hear out @thatandromeda on #233

**Comment by jalperin** [comment]
For the record, yes, splitting the PKP signature into a PKP + my individual names is faithful to the original intent. Appreciate the new organization.

**Comment by jbbowen** [comment]
Please add my name to the list.

Jennifer Bowen

**Comment by ranti** [comment]
@jbbowen : your name has been added to the list. Thank you.

**Comment by tadawes** [comment]
Please add
Trevor A. Dawes 
and
University of Delaware Library
to the list of signatories.  Thanks.

**Comment by eolson3** [comment]
Please add me to the list.  Thank you.

Eric Olson

**Comment by nelsonrr** [comment]
Please add me to the list. Thank you.
Rachelle Nelson

**Comment by ranti** [comment]
@tadawes @eolson3 @nelsonrr Your names have been added to the master list. Added U of Delaware Library as well. Thank you!

**Comment by msheehy** [comment]
Please add me to the list:

Matthew Sheehy

**Comment by bhouston1982** [comment]
Please add my name to the list. Thanks.
Brad Houston

**Comment by ranti** [comment]
@msheehy @bhouston1982 added. Thank you!

**Comment by libsew** [comment]
Please add my name
Susan Wells Parham

**Comment by sbskomal** [comment]
Please add my name to the list
Susan Skomal

**Comment by ranti** [comment]
@libsew @sbskomal added. Thank you.

**Comment by doralyn** [comment]
Could you please add me,  Doralyn Rossmann, to the list? Thank you!

**Comment by clairebrarian** [comment]
Please add my name to the list. Thank you!

**Comment by JenGarrett** [comment]
Can you please add my name to the list, Jennifer Garrett. Thank you!

**Comment by ranti** [comment]
@clairebrarian How do you want your name to be listed?

**Comment by ranti** [comment]
@doralyn @JenGarrett added your name to the list. Thank you!

**Comment by JenGarrett** [comment]
@ranti thank you so much! I have a colleague who would also like her name added, but does not have access to GitHub. Can you please also add - Wendy Scott?

**Comment by TRLN-MAIN** [comment]
Please add the Triangle Research Libraries Network (TRLN) to the list. Thank you!

**Comment by kathryn-gillespie** [comment]
Please add my name to the list

Katie Gillespie

**Comment by charbooth** [comment]
Please add me to the list as well: Char Booth. Thank you.

**Comment by manuelastico** [comment]
On behalf of the Executive Committee of Penn Libraries' Group on Library Diversity (GOLD) please add us to the list

**Comment by mjgiarlo** [comment]
@gmcharlt @matt-bernhardt @ranti @thatandromeda This is ready for another review.

Please note that this PR does not account for the requests above to be added. Can someone add those in a subsequent commit (sorted, naturally)? They are:

### Organizations

* Executive Committee of Penn Libraries' Group on Library Diversity (GOLD)
* Triangle Research Libraries Network (TRLN)

### Individuals

* Char Booth
* Katie Gillespie
* Wendy Scott

**Comment by mjgiarlo** [comment]
And we are waiting to hear back from @clairebrarian re: how to format her name.

**Comment by thatandromeda** [comment]
LGTM in principle. I'm going to assume that you have kept all signatories in the reorganization - I'm not checking individually.

Can we add an issue to clean up the @clairebrarian formatting later so we don't block this merge on it?

Given that, I'm happy with you resolving the conflicts and then merging.

@mjgiarlo @ranti @gmcharlt @yo-bj @nowviskie , let's freeze all other work until @mjgiarlo has landed this one, so that we do not put ourselves in a sad hellscape of merge conflicts.

**Comment by gmcharlt** [comment]
+1 to merge as well, and I'm standing by, frozen.

**Comment by yo-bj** [comment]
+1

**Comment by broadwym** [comment]
+Meredith Broadway, Vanderbilt University

**Comment by mjgiarlo** [comment]
@gmcharlt @thatandromeda @yo-bj OK, it's merged! We'll also need to add Meredith Broadway's name to the backlog.

**Pull request merged**
